services:
  turret:
    container_name: turret-container
    restart: unless-stopped
    working_dir: /app
    command: pnpm dev
    environment:
      - ABSOLUTE_PATH=${ABSOLUTE_PATH:-/home/bmqube/Documents/turret}
      - INTERVAL_TO_CHECK=1000
      - TIME_OUT=60000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
    volumes:
      - ./:/app/
      - /run/user/1000/docker.sock:/var/run/docker.sock
    networks:
      - turret_network

networks:
  turret_network:
    name: turret_network
    driver: bridge
