services:
  turret:
    container_name: turret-container
    restart: unless-stopped
    working_dir: /app
    command: pnpm dev
    # user: "1000:1000"
    environment:
      - DOCKER_HOST=unix:///run/user/1000/docker.sock
    #   - XDG_RUNTIME_DIR=/run/user/1000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
    volumes:
      - ./:/app/
      - /run/user/1000/docker.sock:/run/user/1000/docker.sock
