version: "3.9"
services:
  traefik:
    restart: unless-stopped
    container_name: traefik

    dns:
      - "8.8.8.8"

    ports:
      - target: 80
        published: 80

      - target: 443
        published: 443

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./_DATA/traefik-storage:/traefik-storage

    networks:
      - turret-network

networks:
  turret-network:
    name: turret-network
    external: true
