services:
  test:
    container_name: test-container-1
    restart: unless-stopped
    working_dir: /app
    command: pnpm dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 4000
        published: 4000
    volumes:
      - ./:/app/
