services:
  test:
    restart: unless-stopped
    working_dir: /app
    command: pnpm dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/bmqube/Documents/turret/projects/test1:/app/
    networks:
networks:
  test1_network:
    name: test1_network
    driver: bridge
  turret_network:
    name: turret_network
    external: true
